### PR TITLE
Va cr react router

### PR DESCRIPTION
**Pull request by CrisRuedaP**
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | : New feature             |
|  ✓ | :link: Update dependencies |

## Acceptance Criteria

- [x] **react-router-dom** has been added as a dependency in the project.
- [x] The links are present and remain fixed in the background of the app: one for the "list" view, the other for the "add item" view.
- [x] When one of the links is clicked, the URL is updated in the browser to represent the current view and corresponds to the component displayed.
- [x] Whatever view is selected, the corresponding link must be shown in bold text.

## Related Issue #2

As a user, I want to be able to navigate between the “list” view and the “add an item” view so that the interface is clearly delineated between viewing and adding.

## Description

This PR adds a new file: Router.js in that we configure the routes of the app, also, three new components: **Nav** in which we create the application links, and **ListView** for the list view, and **AddItem** view.

## Updates

We added react-router-dom as a dependency and import the component Router to App.js.

### CODE REVIEW

**Comment by Lukaina** [comment]
Hello, @macosta08 @alxmcr! 

Please take a look at the work we did. We will stay in tune with every correction or suggestion.

Thank you very much!

**Comment by alxmcr** [comment]
Hi @CrisRuedaP and @Lukaina !

**Great work, congratulations!** 🥳

Maybe, it is a little detail, don't worry!  please if it is possible, you could change the text "AddItem" to "Add Item" (with whitespace), please 🙏? I believe that it is much better for our users to visualize two words separately. We'll appreciate it 😄 .

Pd. I have a little doubt about 2nd acceptance criteria, but I'll ask in Slack.

**Comment by CrisRuedaP** [comment]
You right, @alxmcr!

We already did the change. 

Thank you so much. 😊

**Comment by alxmcr** [comment]
Thanks for your improvement with the link "Add Item".

image

Great... Fixed! ✔️

**Comment by Lukaina** [comment]
@alxmcr Hello, thank you very much for the suggestion, it is very valid what you say. 
I already explained the acceptance criteria #2

@CrisRuedaP Thank you very much for the change you made.

**Comment by Lukaina** [comment]
@alxmcr Okay, I will try to explain this criterion as clearly as possible. 

When he refers to the fact that the links must be present and always fixed in the background, he means that if you are at Home for example, the links will be there, if you go to the list page, the links will be there and if you go to another page, whatever it is, they must be there. Because if you look at the application: https://app.ineedtobuy.xyz/add
And you navigate through any page, the buttons at the bottom are always there, those buttons are just the links.

I hope you have made me understand and if not, I write you for Slack.

**Comment by alxmcr** [comment]
> @alxmcr Okay, I will try to explain this criterion as clearly as possible.
> 
> When he refers to the fact that the links must be present and always fixed in the background, he means that if you are at Home for example, the links will be there, if you go to the list page, the links will be there and if you go to another page, whatever it is, they must be there. Because if you look at the application: https://app.ineedtobuy.xyz/add
> And you navigate through any page, the buttons at the bottom are always there, those buttons are just the links.
> 
> I hope you have made me understand and if not, I write you for Slack.

Yes, I understand it much better (plus your Slack's explanation is great). Thank you so much!

**Review by Lukaina — COMMENTED** [review]
Thanks a lot, partner @CrisRuedaP! Great job!

**Comment by alxmcr** [comment]
Great! Thanks for adding the styles!

image

Styles added ✔️! Thank you so much @CrisRuedaP and @Lukaina !

My review is finished ✔️. I agree with all 😄 . 

(PS: Maybe, @macosta08 will have any comments)

**Review by alxmcr — APPROVED** [review]
Sorry! I forgot to check as reviewed the files. Approved ✔️.

**Review by macosta08 — APPROVED** [review]
Verónica and Cristina seem to me that their code is very well structured, separated into several components when generating the routes. Excellent!!!

**Comment by Lukaina** [comment]
Thank you very much, @macosta08 @alxmcr! You have also made a great effort and work.

**Review by gmzjuliana — APPROVED** [review]
nice! LGTM 👏

**Review by indiragp — APPROVED** [review]
Great job! Also to the reviewers and making updates promptly :)

**Pull request merged**
